# Generated by Django 5.1.3 on 2024-12-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
